<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Stingray.Core.Tests" />
  </ItemGroup>
</Project>
